import type { Metadata } from "next";
import "./globals.css";
import Datacontext from "@/src/context/Datacontext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Datacontext>

      <html lang="en">
        <body>
          {children}
        </body>
      </html >
    </Datacontext>
  );
}
